server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: payment8001
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 100
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 200

#eureka:
#  instance:
#    hostname: localhost
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 15
#    instance-id: ${spring.application.name}
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
#    enabled: true
#    register-with-eureka: true
#    fetch-registry: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wm.springcloud.entity