server:
  port: 80

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  eureka:
    enabled: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

logging:
  level:
    com.wm.springcloud.service.PaymentFeignService: debug

